version: "3"

services:
  app:
    image: my-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
