name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/unit
        pytest models/test_scan_network.py
        pytest models/test_check_asn.py
        pytest models/test_threat_analysis.py
        pytest models/test_ip_geolocation.py
        pytest models/test_check_breaches.py
        pytest models/test_scan_ip.py
        pytest models/test_api_search.py
        pytest models/test_crypto_check.py
        pytest models/test_domain_scanner.py
        # pytest models/test_extract_metadata.py # disable this test for now
